apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - image: CONTAINER_IMAGE
          imagePullPolicy: Always
          name: cicd-demo
          ports:
            - containerPort: 8080
